dist: bionic

language: scala

scala: 
  - "2.12.12"

jdk: oraclejdk11

cache:
  directories:
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

install:
  - git fetch --tags

script:
   - sbt ++$TRAVIS_SCALA_VERSION clean headerCheck scalastyle test:scalastyle coverage test coverageReport scripted

before_deploy:
  - if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      openssl aes-256-cbc -K $encrypted_82c15cb04022_key -iv $encrypted_82c15cb04022_iv -in secring.asc.enc -out secring.asc -d;
      gpg --batch --import secring.asc;
      rm secring.asc;
    fi

deploy:
  - provider: script
    skip_cleanup: true
    script: sbt ++$TRAVIS_SCALA_VERSION coverageOff publishSigned
    on:
      tags: false
      all_branches: true
  - provider: script
    skip_cleanup: true
    script: sbt ++$TRAVIS_SCALA_VERSION coverageOff publishSigned sonatypeBundleRelease
    on:
      tags: true

env:
  global:
    - secure: "Dyou8X40mNMoTLcthuYpTtsBhChI+WFj+q6biyotgXTwlo7nkRRsQLZ+R/BoVWBoG2rToAS8PWjF7ivf9G4rWuI6d4snIVjoLfv7xYZkHDkjK2QoeyCVbuhb5hyPvzG+c6TGe1AQI0r04WwMOSpYyysX2JGz5WOlgnPRPGObyNx46KgsEQk17JUjRt4siyYsfDATqvtTohgZlXlSWP/OlQ4uGB22Rm2PtaWTF3rav/cVFe6NpTATO9gJQbFrBiTDEJLnhdj3fzVcFbFQlxkG+x56SMTaTLM0TzMW8SOoUgzZQrA73DhIUJey2S4ou0UjaH9trFS15CaD0B24z0Cw7nuAn8bQ1e0FcO7xcX2RCamiRYf4i7bnvUuTwRBhGDf6Zl/R7b4yNx8oPkgOCLi2OiTZXePDihhjUOrNl2m81drkDW7SRsaOpgONiU7tObtNqhI8Rp4i6qdEbb9seu/pmmESxqDxm8WnmtbuTZd1DEXLDxpiXHmTtKWFMReLc+bsovwsP1BDzBSOmszkn9aET/A+u7dvXfix2A+eCREOajjJM7zqXEUz4dj9F7AlgpzwksI4Vxd4Y0Oddz/ggTGzMa0NC8Q1J7xH6U5HndgXwcxcjhyybIb4iXo0he9x0ZOhOtOrNYqU5fJWKjvviBNxUVSE8/egqkiPpzvI8qou8/4="
    - secure: "gQ5T9svgcREAP4PpNHXrWDs9iAzVRtlWn8UDUKC6s7q53hDTW3qZEV7Qm+TQK3Drju2wfh1uhcIB4vzOfeoNf7e1CYsw9CArrabRpQCFCVlbZLwxeFx+5DpWTks87xAYKX3EEnAIqlbv6Qf9Ui4j1yJeNGP5990vJ1ohRQOrFtWKrQdplhBXDS/oX2GbpLhIswkp0I3IaTh1mwfupeZgSFc75aDdXtPXY8z2EuvJCS3BZ9oBXJ2gNrAIvh18bEJQHu98dzbG67UrcPgk4S9sPFkx/A6oY2eal7DrfBxWcqo9rforMaeltmz1+yIvG9rJJOlU9FLU8gYkGrnA0r0arUGAW7EvFs2PsihljgF+wxxOJqhdqbq8BdtgBSSNdEpNDQSQU/jSpdm4Ug0d9zllwcOBp9tR7ToAmfY0D9YrwJjEiMZMm9AFtaq5r7CQ7pj57TQB19b9zyhi9XiCM3y/BkAVLDIAMmtGx/qDXizeBrNU9nObejfX1jrrchlk6T2i75O25FA2tMqfi/Ydyj169ehKHsvCultJl9Yyp/CyRFVaj4AxoHBQJiIuZFxUvoX8khlJOBXSiDMkRPappkm9/CH0kYLz1YF3+CINCyVpP71mmeWZBq12U5RXT6tSI6Jk7H0uARTz8AJvpdUkpp0yqrpntJT6PMnHtWC2BwNMb6E="
    - secure: "izc9X8+dk7W+VuFRj2P8QH+f7eHLRs5PlCE6OZB4UvWIpo8IrduEeLeANHpgSYFWuSVNtgKf7GWvzY43iXUAAsXo5dEYmMcDcl/kg30a+sfGs4z2G/dshS1MZyE5qcfRwcya1KtWD4werqU5/2ms+/nfcJEjfC97KU6cKFTasBKI2r3wEzuY5BEiSWUpdrrp+RnziMBEx3oI0r3rVm0JDsvT51m8e99mM252oVs4EMoo2NbAcsNckgCod5liMxG/0ABI3gJzsfhH0tpQICM7BVCjG5hUegECiDlhVHmARPhk4cPm/Owaqq7VxBqLZ0ds6T9UZUq6L5BU0HJG96T3Zj28ZmHumoPXoQ84iX0pMnfFtrvLSqLOJm4AuQTAEWA+LPRCmURzN6QYxgkWqd/Ux6NsOxuv5qteNN/WaA35DKnTFXEDkN+cSedMQh93oNFOGgIedkS+lPJfwl6xb7qLW60Cv9jsKfXodHQ9gD0yj/cxwdc0gUdr3b6MSGPXoXaOUfa3rs8KoF4ls9yVozHnbRfN4dI6rYFs+SnwSeyPSXLVitXTXBiK3uHJ3gbgtin8Pyq75JcDM/ra8w1+6379T6UksSzKNACrzdvwjIkCKKyBHCbJzx66fItNcTcij1+nhvY6nOLqn3HKrF8F1i8jIrpdgUU9w5ScEz1jhO3TYfw="
